BEGIN;

ALTER TABLE payments ADD COLUMN IF NOT EXISTS gross_amount DECIMAL(12,2);
ALTER TABLE payments ADD COLUMN IF NOT EXISTS discount_amount DECIMAL(12,2) DEFAULT 0;

ALTER TABLE accounting_invoices ADD COLUMN IF NOT EXISTS case_id UUID REFERENCES cases(id) ON DELETE SET NULL;

COMMIT;
